# Generated by Django 5.0.14 on 2025-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_address',
            field=models.CharField(max_length=30),
        ),
    ]
