# Generated by Django 5.0.14 on 2025-07-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_alter_employee_emp_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_salarry',
            new_name='emp_salary',
        ),
    ]
