# Generated by Django 5.0.14 on 2025-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_rename_emp_salarry_employee_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_Contact',
            field=models.CharField(max_length=30),
        ),
    ]
